### ISSUE TITLE
Support tickets in leaflet-omnivore updated from Wed Sep 09 2015 to Fri Oct 09 2015

### ISSUE THREAD

**Issue by lyzidiamond** [lyzidiamond/mapbox-support#220]
- [ ] <a href="https://github.com/mapbox/leaflet-omnivore/issues/64">Lag on csv load from http?</a>
- [ ] <a href="https://github.com/mapbox/leaflet-omnivore/issues/61">Different behaviour in minified code</a>
- [ ] <a href="https://github.com/mapbox/leaflet-omnivore/issues/57">Global .jshintrc was causing project not to build</a>
