### ISSUE TITLE
Support tickets in mapbox-android-sdk updated from Wed Sep 09 2015 to Fri Oct 09 2015

### ISSUE THREAD

**Issue by lyzidiamond** [lyzidiamond/mapbox-support#224]
- [ ] <a href="https://github.com/mapbox/mapbox-android-sdk/issues/835">FloatMath removed in marshmallow </a>
- [ ] <a href="https://github.com/mapbox/mapbox-android-sdk/issues/834">Build Exception</a>
- [ ] <a href="https://github.com/mapbox/mapbox-android-sdk/issues/833">NullPointerException in MapView.onDraw() after many marker updates</a>
- [ ] <a href="https://github.com/mapbox/mapbox-android-sdk/pull/832">Add "DoubleTapMap" to the MapViewListener</a>
- [ ] <a href="https://github.com/mapbox/mapbox-android-sdk/pull/831">fix typo in MBTilesLayer javadoc</a>
- [ ] <a href="https://github.com/mapbox/mapbox-android-sdk/pull/830">Custom AnimatorListener throw zoomToBoundingBox</a>
- [ ] <a href="https://github.com/mapbox/mapbox-android-sdk/issues/829">Detect tap on ClusterMarker</a>
- [ ] <a href="https://github.com/mapbox/mapbox-android-sdk/issues/828">onTapMarker : Switch focus between 2 markers</a>
- [ ] <a href="https://github.com/mapbox/mapbox-android-sdk/issues/827">InfoWindow Click or Touch Not working</a>
- [ ] <a href="https://github.com/mapbox/mapbox-android-sdk/issues/825">Garbage production</a>
- [ ] <a href="https://github.com/mapbox/mapbox-android-sdk/issues/823">The map flickers after a particular zoom level when 3 or more layers((overlays) are added on the basemap.</a>
- [ ] <a href="https://github.com/mapbox/mapbox-android-sdk/issues/811">onZoom() of MapListener Interface isn't called on Pinch gesture.</a>
- [ ] <a href="https://github.com/mapbox/mapbox-android-sdk/issues/806">Proplems with PathOverlay and Hardware Acceleration</a>
