### ISSUE TITLE
Support tickets in mapbox-gl-js updated from Wed Sep 09 2015 to Fri Oct 09 2015

### ISSUE THREAD

**Issue by lyzidiamond** [lyzidiamond/mapbox-support#229]
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1600">Bump geojson-vt dep version</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1597">WebGL switching to software rendering more frequently with recent changes</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1594">How to implement markers that can be scaled and recoloured?</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1590">map.addControl(new mapboxgl.Navigation())   has a bug in v 0.11.1</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1566">clickable marker popup</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1563">MapBox GL possible bug: Not all labels rendered when using a symbol-placement of line</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1554">Just compass</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1533">Max value for options.speed?</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1496">Disable touch rotation</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1489">3D terrain meshes</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1485">Adding Custom Attribution</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1477">remove then re add a Popup doesn't work and causes an error</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1473">API: fitBounds without an animation</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1466">Support for non-mercator projections? </a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1442">Drag events</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1437">Rendering broken in Microsoft Edge</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1374">GeoJSON marker text glyphs ignore text-allow-overlap</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1353">Feature request: Cursor 'pointer' on interactive layers</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1322">Build fails on Windows when running node docs : FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1270">raster layer with opacity < 1 flickers to full opacity</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1203">Marker movement example in mapbox-gl-js?</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/1093">Vector tile data rendered incorrectly if extent != 4096</a>
- [ ] <a href="https://github.com/mapbox/mapbox-gl-js/issues/656">Add support for markers</a>
