### ISSUE TITLE
Support tickets in mapbox-studio-classic updated from Wed Sep 09 2015 to Fri Oct 09 2015

### ISSUE THREAD

**Issue by lyzidiamond** [lyzidiamond/mapbox-support#230]
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/pull/1478">Unix socket support when running studio as server</a>
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/issues/1476">No projects drawer /new projects button - Ubuntu?</a>
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/issues/1472">MapBOX 0.3.1 doesn't open old projects</a>
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/issues/1470">MapBox Studio Classic 0.3.1 - kartotherian/osm-bright.tm2</a>
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/issues/1469">can't export tm2 file?</a>
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/issues/1467">Ability to export project mapnik XML</a>
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/issues/1466">Crash on Startup</a>
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/issues/1461">Layers/change source does not allow query strings</a>
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/issues/1454">Max value for layer buffer slider is 64, but sometimes larger values are needed</a>
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/issues/1452">App not working</a>
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/issues/1450">Cannot find Mapbox API at https://a.tiles.mapbox.com</a>
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/issues/1447">Error: Error calculating min/max zoom: Bounds invalid</a>
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/issues/1160">Raster and vector layers in the same source project</a>
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/issues/983">Relative paths</a>
- [ ] <a href="https://github.com/mapbox/mapbox-studio-classic/issues/574">Select and style specified raster source bands</a>
