### ISSUE TITLE
Support tickets in mapbox.js updated from Wed Sep 09 2015 to Fri Oct 09 2015

### ISSUE THREAD

**Issue by lyzidiamond** [lyzidiamond/mapbox-support#232]
- [ ] <a href="https://github.com/mapbox/mapbox.js/issues/1062">Slow loading tiles, javascript lockup when zooming in Chrome</a>
- [ ] <a href="https://github.com/mapbox/mapbox.js/issues/1061">Only one of two features in the GeoJSON file was displayed</a>
- [ ] <a href="https://github.com/mapbox/mapbox.js/issues/1060">Don't autoattach window.L on require()</a>
- [ ] <a href="https://github.com/mapbox/mapbox.js/issues/1058">Arrow down to autocomplete results in geocoding box</a>
