### ISSUE TITLE
Support tickets in node-sqlite3 updated from Wed Sep 09 2015 to Fri Oct 09 2015

### ISSUE THREAD

**Issue by lyzidiamond** [lyzidiamond/mapbox-support#240]
- [ ] <a href="https://github.com/mapbox/node-sqlite3/pull/523">Add sync versions of exec, run, get, all methods</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/522">Getting error while installing serialport module</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/521">Build for nw.js v0.12.3 in order to use child_process.fork ?</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/520">API Wiki Page - Gone Missing</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/519">Install failed from Ubuntu 15.04 and Node.js 4.1.1</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/pull/518">Add support for sqlite3_interrupt</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/515">Does db.serialize support full ACID feature?</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/513">npm rebuild does not appear to actually rebuild</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/512">Uncaught TypeError: Cannot read property '_ansicursor' of undefined</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/pull/507">mapbox/node-sqlite3/issues/503 test</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/503">stmt.finalize(callback) can't promise the sequence</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/501">ERR!: can´t install node-sqlite3 on my Raspberry Pi 2</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/499">unable to install on FreeBSD 9.3-STABLE</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/497">Unable to build sqlite3 for nwjs (node-webkit)</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/496">Cannot install in folder with node_modules part in name</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/493">Out of date wiki link?</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/492">sqlite3 installation on Debian 8 64-bit.</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/pull/451">Added declared type values as 3rd argument to callbacks</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/357">atom-shell</a>
- [ ] <a href="https://github.com/mapbox/node-sqlite3/issues/345">no windows 8.1 x64 binary?</a>
